coverage:
    ignore:
       - "src/learners/gradient_descent.jl"
    project:
      default:
        threshold: 0.5%
        removed_code_behavior: fully_covered_patch
    patch:
      default:
        target: 80
